trigger:
- none

pool:
  DevOps-Poool

variables:
  workingDirectory: environment/dev

steps:
- task: TerraformInstaller@1
  displayName: Terraform Installer
  inputs:
   terraformVersion: latest

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: "$(workingDirectory)"
    backendServiceArm: 'Service Connection'
    backendAzureRmResourceGroupName: 'rg-demon-slayer'
    backendAzureRmStorageAccountName: 'luciferstorageacc'
    backendAzureRmContainerName: 'lucifercontainer'
    backendAzureRmKey: 'firehashira.tfstate'

- task: TerraformTask@5
  displayName: Terraform Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: "$(workingDirectory)"

- task: TerraformTask@5
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: "$(workingDirectory)"
    environmentServiceNameAzureRM: 'Service Connection'

- task: TerraformTask@5
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: "$(workingDirectory)"
    environmentServiceNameAzureRM: 'Service Connection'